drop sequence SICOES_SEQ_USUARIO;
drop sequence SICOES_SEQ_USUARIO_ROL;
create sequence SICOES_SEQ_USUARIO START WITH 120;
create sequence SICOES_SEQ_USUARIO_ROL START WITH 124;

GRANT SELECT ON  SICOES_SEQ_USUARIO TO US_SICOES ;
GRANT SELECT ON  SICOES_SEQ_USUARIO_ROL TO US_SICOES ;