
CREATE TABLE SICOES_TC_REQ_RENOVACION 
    ( 
     ID_REQ_RENOVACION     NUMBER  NOT NULL , 
     ID_SOLI_PERF_CONT     NUMBER (38) , 
     ID_USUARIO            NUMBER (10) , 
     NU_EXPEDIENTE         VARCHAR2 (50)  NOT NULL , 
     TI_SECTOR             VARCHAR2 (100)  NOT NULL , 
     TI_SUB_SECTOR         VARCHAR2 (100)  NOT NULL , 
     NO_ITEM               VARCHAR2 (100)  NOT NULL , 
     FE_REGISTRO           DATE DEFAULT SYSDATE  NOT NULL , 
     ES_REQ_RENOVACION     NUMBER (10)  NOT NULL , 
 
     DE_OBSERVACION        VARCHAR2 (500) , 
     ES_REGISTRO           CHAR (1) NOT NULL , 
     US_CREACION           VARCHAR2 (38)  NOT NULL , 
     IP_CREACION           VARCHAR2 (38)  NOT NULL , 
     FE_CREACION           DATE DEFAULT SYSDATE  NOT NULL , 
     US_ACTUALIZACION      VARCHAR2 (38) , 
     IP_ACTUALIZACION      VARCHAR2 (38) , 
     FE_ACTUALIZACION      DATE 
    ) 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.ID_REQ_RENOVACION IS 'ID del Requerimiento de renovación' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.ID_SOLI_PERF_CONT IS 'Fk de la solicitud de perfeccionamiento de contrato' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.ID_USUARIO IS 'ID del usuario que genera el requerimiento de renovación' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.NU_EXPEDIENTE IS 'Número de expediente' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.TI_SECTOR IS 'Tipo de sector al que pertenece la empresa supervisora' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.TI_SUB_SECTOR IS 'Tipo de subsector al que pertenece la empresa supervisora' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.NO_ITEM IS 'Nombre del item' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.FE_REGISTRO IS 'Fecha de registro del requerimiento de renovación' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.ES_REQ_RENOVACION IS 'Estado del requerimiento de renovación' 
;


 

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.DE_OBSERVACION IS 'Observación de la creación del requerimiento' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.ES_REGISTRO IS 'Estado del registro 1: Activo 0:Inactivo' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.US_CREACION IS 'Usuario que ha creado el registro' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.IP_CREACION IS 'IP del equipo de donde se ha creado  el registro' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.FE_CREACION IS 'Fecha de creación del registro' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.US_ACTUALIZACION IS 'Usuario que modificó el registro' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.IP_ACTUALIZACION IS 'IP del equipo de donde se ha modificado el registro' 
;

COMMENT ON COLUMN SICOES_TC_REQ_RENOVACION.FE_ACTUALIZACION IS 'Fecha en que se ha actualizado el registro' 
;

ALTER TABLE SICOES_TC_REQ_RENOVACION 
    ADD CONSTRAINT SICOES_TC_REQ_RENOVACION_PK PRIMARY KEY ( ID_REQ_RENOVACION ) ;




CREATE TABLE SICOES_TD_INFORME_RENOVACION --NUEVO
    ( 
     ID_INFORME_RENOVACION   NUMBER  NOT NULL , 
     ID_USUARIO              NUMBER (10) NOT NULL, 
     ID_NOTIFICACION         NUMBER (10) , 
     ID_REQUERIMIENTO        NUMBER  NOT NULL , 
     DE_OBJETO               CLOB , 
     DE_BASE_LEGAL           CLOB , 
     DE_ANTECEDENTES         CLOB , 
     DE_JUSTIFICACION        CLOB , 
     DE_NECESIDAD            CLOB , 
     DE_CONCLUSIONES         CLOB , 
     ES_VIGENTE              NUMBER (1)  NOT NULL , 
     ES_APROBACION_INFORME NUMBER(10) NOT NULL,
     DE_UUID_INFO_RENOVACION CHAR (36)  NOT NULL , 
     DE_NOMBRE_ARCHIVO       VARCHAR2 (100) , 
     DE_RUTA_ARCHIVO         VARCHAR2 (100) , 
	 ES_COMPLETADO           CHAR (1) NOT NULL,
     US_CREACION             VARCHAR2 (38)  NOT NULL , 
     IP_CREACION             VARCHAR2 (38)  NOT NULL , 
     FE_CREACION             DATE DEFAULT SYSDATE  NOT NULL , 
     US_ACTUALIZACION        VARCHAR2 (38) , 
     IP_ACTUALIZACION        VARCHAR2 (38) , 
     FE_ACTUALIZACION        DATE , 
     ES_REGISTRO             CHAR (1) NOT NULL
    ) 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.ID_INFORME_RENOVACION IS 'Identificador del Informe de Renovación' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.ID_USUARIO IS 'FK del usuario que genera el informe' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.ID_NOTIFICACION IS 'FK de la notificación asociada a la creación del informe' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.ID_REQUERIMIENTO IS 'FK del Requerimiento de Renovación' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.DE_OBJETO IS 'Descripción del Objeto del Informe' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.DE_BASE_LEGAL IS 'Descripción de la base legal  del Informe' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.DE_ANTECEDENTES IS 'Descripción de los antecedentes considerados en el IInforme' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.DE_JUSTIFICACION IS 'Descripción de la justificación  del Informe' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.DE_NECESIDAD IS 'Descripción de la necesidad  del Informe' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.DE_CONCLUSIONES IS 'Descripción de las conclusiones  del Informe' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.ES_VIGENTE IS 'Estado del Informe 1: Activo 0: Desactivo' 
;
COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.ES_APROBACION_INFORME IS 'Estado de aprobación del informe de renovación';

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.DE_UUID_INFO_RENOVACION IS 'Identificador único del Informe de Renovación en el repositorio de archivo' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.DE_NOMBRE_ARCHIVO IS 'Nombre del archivo del informe de renovación' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.DE_RUTA_ARCHIVO IS 'Ruta donde se deposita el archivo del informe' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.US_CREACION IS 'Usuario que ha creado el registro' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.IP_CREACION IS 'IP del equipo de donde se ha creado  el registro' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.FE_CREACION IS 'Fecha de creación del registro' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.US_ACTUALIZACION IS 'Usuario que modificó el registro' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.IP_ACTUALIZACION IS 'IP del equipo de donde se ha modificado el registro' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.FE_ACTUALIZACION IS 'Fecha en que se ha actualizado el registro' 
;

COMMENT ON COLUMN SICOES_TD_INFORME_RENOVACION.ES_REGISTRO IS 'Estado del registro 1: Activo 0:Inactivo' 
;

ALTER TABLE SICOES_TD_INFORME_RENOVACION 
    ADD CONSTRAINT SICOES_TD_INFO_REN_PK PRIMARY KEY ( ID_INFORME_RENOVACION ) ;



CREATE TABLE SICOES_TM_PLAZO_CONFIRMACION ---NUEVO
    ( 
     ID_PLAZO_CONFIRMACION NUMBER  NOT NULL , 
     FE_BASE               VARCHAR2 (38)  NOT NULL , 
     IN_TIPO_DIA           NUMBER (*,0)  NOT NULL , 
     NU_DIAS               NUMBER (5)  NOT NULL , 
     ES_REGISTRO           CHAR (1)  NOT NULL , 
     US_CREACION           VARCHAR2 (38)  NOT NULL , 
     IP_CREACION           VARCHAR2 (38)  NOT NULL , 
     FE_CREACION           DATE DEFAULT SYSDATE  NOT NULL , 
     US_ACTUALIZACION      VARCHAR2 (38) , 
     IP_ACTUALIZACION      VARCHAR2 (38) , 
     FE_ACTUALIZACION      DATE 
    ) 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.ID_PLAZO_CONFIRMACION IS 'ID del plazo de confirmación' 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.FE_BASE IS 'Fecha base' 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.IN_TIPO_DIA IS 'Indicador de dia calendario:  1:Día Calendario , 2:Dia Hábil' 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.NU_DIAS IS 'Número de días a considerar en el cálculo dela fecha plazo confirmación' 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.ES_REGISTRO IS 'Estado del registro 1: Activo 0:Inactivo' 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.US_CREACION IS 'Usuario que ha creado el registro' 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.IP_CREACION IS 'IP del equipo de donde se ha creado  el registro' 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.FE_CREACION IS 'Fecha de creación del registro' 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.US_ACTUALIZACION IS 'Usuario que modificó el registro' 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.IP_ACTUALIZACION IS 'IP del equipo de donde se ha modificado el registro' 
;

COMMENT ON COLUMN SICOES_TM_PLAZO_CONFIRMACION.FE_ACTUALIZACION IS 'Fecha de actualización del registro' 
;


ALTER TABLE SICOES_TM_PLAZO_CONFIRMACION                    
    ADD CONSTRAINT SICOES_TM_PL_CONF_PK PRIMARY KEY ( ID_PLAZO_CONFIRMACION ) ;



CREATE TABLE SICOES_TZ_HIST_EST_APROB_CAMPO 
    ( 
     ID_HISTORIAL_ESTADO_CAMPO NUMBER  NOT NULL , 
     ID_REQ_APROBACION         NUMBER (38)  NOT NULL,
     ID_GRUPO_LD      NUMBER (38),
     ID_GRUPO_APROBADOR_LD     NUMBER (38),
     ID_USUARIO                NUMBER (10) NOT NULL , 
     DE_ESTADO_ANTERIOR_LD     NUMBER (10) NOT NULL , 
     DE_ESTADO_NUEVO_LD        NUMBER (10)  NOT NULL ,      
     FE_FECHA_CAMBIO           TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL , 
     ES_REGISTRO               CHAR (1)  NOT NULL , 
     US_CREACION               VARCHAR2 (38)  NOT NULL , 
     IP_CREACION               VARCHAR2 (38)  NOT NULL , 
     FE_CREACION               DATE DEFAULT SYSDATE  NOT NULL , 
     US_ACTUALIZACION          VARCHAR2 (38) , 
     IP_ACTUALIZACION          VARCHAR2 (38) , 
     FE_ACTUALIZACION          DATE 
    ) 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.ID_HISTORIAL_ESTADO_CAMPO IS 'ID DEL HISTORIAL DE APROBACIÓN' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.ID_REQ_APROBACION IS 'FK DEL REQUERIMIENTO DE APROBACION' ;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.ID_GRUPO_LD IS 'Foranea de la tabla SICOES_TM_LISTADO_DETALLE que contiene el tipo aprobador. Por ejemplo: 544 - Aprobador Técnico' ;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.ID_GRUPO_APROBADOR_LD IS 'Foranea de la tabla SICOES_TM_LISTADO_DETALLE que contiene el grupo aprobador. Por ejemplo: 954:Jefe de Unidad, 955: Gerente, 956: GPPM, 957:GSE ' ;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.ID_USUARIO IS 'FK del usuario que realizó el cambio de estado' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.DE_ESTADO_ANTERIOR_LD IS 'Valor del campo Estado previo a la actualización' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.DE_ESTADO_NUEVO_LD IS 'Valor del campo Estado luego  a la actualización' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.FE_FECHA_CAMBIO IS 'Fecha en que se ha realizado el cambio de estado' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.ES_REGISTRO IS 'Estado del registro 1: Activo 0:Inactivo' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.US_CREACION IS 'Usuario que ha creado el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.IP_CREACION IS 'IP del equipo de donde se ha creado  el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.FE_CREACION IS 'Fecha de creación del registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.US_ACTUALIZACION IS 'Usuario que modificó el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.IP_ACTUALIZACION IS 'IP del equipo de donde se ha modificado el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_APROB_CAMPO.FE_ACTUALIZACION IS 'Fecha de actualización  del registro' 
;


ALTER TABLE SICOES_TZ_HIST_EST_APROB_CAMPO 
    ADD CONSTRAINT SCS_TZ_H_AP_CAMPO_PK PRIMARY KEY ( ID_HISTORIAL_ESTADO_CAMPO ) ;
	
	

CREATE TABLE SICOES_TZ_HIST_EST_INVITACION --NUEVO
    ( 
     ID_HISTORIAL_INVITACION NUMBER  NOT NULL , 
     ID_REQ_INVITACION       NUMBER (38)  NOT NULL , 
     DE_ESTADO_ANTERIOR      VARCHAR2 (20) , 
     DE_ESTADO_NUEVO         VARCHAR2 (20)  NOT NULL , 
     FE_FECHA_CAMBIO         TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL , 
     ID_USUARIO              NUMBER (10)  NOT NULL , 
     ES_REGISTRO             CHAR (1) NOT NULL, 
     US_CREACION             VARCHAR2 (38)  NOT NULL , 
     IP_CREACION             VARCHAR2 (38)  NOT NULL , 
     FE_CREACION             DATE DEFAULT SYSDATE  NOT NULL , 
     US_ACTUALIZACION        VARCHAR2 (38) , 
     IP_ACTUALIZACION        VARCHAR2 (38) , 
     FE_ACTUALIZACION        DATE 
    ) 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.ID_HISTORIAL_INVITACION IS 'ID del historal de invitación' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.ID_REQ_INVITACION IS 'FK de la invitación' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.DE_ESTADO_ANTERIOR IS 'Estado anterior a la actualización' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.DE_ESTADO_NUEVO IS 'Estado nuevo, posterior  a la actualización' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.FE_FECHA_CAMBIO IS 'Fecha en que se ha realizado el cambio de estado' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.ID_USUARIO IS 'FK del usuario que realizó el cambio de estado' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.ES_REGISTRO IS 'Estado del registro 1: Activo 0:Inactivo' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.US_CREACION IS 'Usuario que ha creado el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.IP_CREACION IS 'IP del equipo de donde se ha creado  el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.FE_CREACION IS 'Fecha de creación del registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.US_ACTUALIZACION IS 'Usuario que modificó el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.IP_ACTUALIZACION IS 'IP del equipo de donde se ha modificado el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_INVITACION.FE_ACTUALIZACION IS 'Fecha de actualización del registro' 
;


ALTER TABLE SICOES_TZ_HIST_EST_INVITACION 
    ADD CONSTRAINT SCS_TZ_H_EST_INV_PK PRIMARY KEY ( ID_HISTORIAL_INVITACION ) ;
	


CREATE TABLE SICOES_TZ_HIST_EST_REQ_RENOV --NUEVO
    ( 
     ID_HISTORIAL_ESTADO_CAMPO NUMBER  NOT NULL , 
     ID_REQUERIMIENTO          NUMBER  NOT NULL , 
     ID_USUARIO                NUMBER (10) , 
     DE_ESTADO_ANTERIOR_LD     NUMBER (10) , 
     DE_ESTADO_NUEVO_LD        NUMBER (10)  NOT NULL , 
     FE_FECHA_CAMBIO           TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL , 
     ES_REGISTRO               CHAR (1) NOT NULL , 
     US_CREACION               VARCHAR2 (38)  NOT NULL , 
     IP_CREACION               VARCHAR2 (38)  NOT NULL , 
     FE_CREACION               DATE DEFAULT SYSDATE  NOT NULL , 
     US_ACTUALIZACION          VARCHAR2 (38) , 
     IP_ACTUALIZACION          VARCHAR2 (38) , 
     FE_ACTUALIZACION          DATE 
    ) 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.ID_HISTORIAL_ESTADO_CAMPO IS 'ID del historial del estado del Requerimiento de Renovación' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.ID_REQUERIMIENTO IS 'FK del requerimiento de renovación' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.ID_USUARIO IS 'FK del usuario que realizó la actualización del campo ' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.DE_ESTADO_ANTERIOR_LD IS 'Valor del estado anterior a la actualización' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.DE_ESTADO_NUEVO_LD IS 'Valor del nuevo estado luego de la actualización' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.FE_FECHA_CAMBIO IS 'Fecha en que se ha realizado el cambio de estado' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.ES_REGISTRO IS 'Estado del registro 1: Activo 0:Inactivo' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.US_CREACION IS 'Usuario que ha creado el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.IP_CREACION IS 'IP del equipo de donde se ha creado  el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.FE_CREACION IS 'Fecha de creación del registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.US_ACTUALIZACION IS 'Usuario que modificó el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.IP_ACTUALIZACION IS 'IP del equipo de donde se ha modificado el registro' 
;

COMMENT ON COLUMN SICOES_TZ_HIST_EST_REQ_RENOV.FE_ACTUALIZACION IS 'Fecha de actualización  del registro' 
;

ALTER TABLE SICOES_TZ_HIST_EST_REQ_RENOV 
    ADD CONSTRAINT SICOES_TZ_HIST_EST_REQ_RENOV_PK PRIMARY KEY ( ID_HISTORIAL_ESTADO_CAMPO ) ;

CREATE TABLE SICOES_TZ_INF_PRESUPUESTAL --NUEVO
    ( 
     ID_INF_PRESUPUESTAL NUMBER  NOT NULL , 
     ID_REQ_APROBACION   NUMBER (38) , 
     DE_UUID_ARCHIVO     CHAR (36)  NOT NULL , 
     DE_NOMBRE_ARCHIVO   VARCHAR2 (100)  NOT NULL , 
     DE_RUTA_ARCHIVO     VARCHAR2 (100)  NOT NULL , 
     FE_CARGA            DATE  NOT NULL , 
     ES_REGISTRO         CHAR (1)  NOT NULL , 
     US_CREACION         VARCHAR2 (38)  NOT NULL , 
     IP_CREACION         VARCHAR2 (38)  NOT NULL , 
     FE_CREACION         DATE DEFAULT SYSDATE  NOT NULL , 
     US_ACTUALIZACION    VARCHAR2 (38) , 
     IP_ACTUALIZACION    VARCHAR2 (38) , 
     FE_ACTUALIZACION    DATE 
    ) 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.ID_INF_PRESUPUESTAL IS 'ID del informe presupuestal' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.ID_REQ_APROBACION IS 'FK del Requerimiento de Aprobación' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.DE_UUID_ARCHIVO IS 'Identificador del archivo adjunto' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.DE_NOMBRE_ARCHIVO IS 'Nombre del archivo adjunto' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.DE_RUTA_ARCHIVO IS 'Ruta donde se aloja el archivo adjunto' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.FE_CARGA IS 'Fecha de carga de archivo' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.ES_REGISTRO IS 'Estado del registro 1: Activo 0:Inactivo' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.US_CREACION IS 'Usuario que ha creado el registro' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.IP_CREACION IS 'IP del equipo de donde se ha creado  el registro' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.FE_CREACION IS 'Fecha de creación del registro' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.US_ACTUALIZACION IS 'Usuario que modificó el registro' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.IP_ACTUALIZACION IS 'IP del equipo de donde se ha modificado el registro' 
;

COMMENT ON COLUMN SICOES_TZ_INF_PRESUPUESTAL.FE_ACTUALIZACION IS 'Fecha de actualización del registro' 
;

ALTER TABLE SICOES_TZ_INF_PRESUPUESTAL 
    ADD CONSTRAINT SICOES_TZ_INF_PRESUPUESTAL_PK PRIMARY KEY ( ID_INF_PRESUPUESTAL ) ;
	
    

--------ALTERS--------

ALTER TABLE SICOES_TZ_HIST_EST_APROB_CAMPO 
    ADD CONSTRAINT FK_ESTADO_APROBACION_02 FOREIGN KEY 
    ( 
     ID_REQ_APROBACION
    ) 
    REFERENCES ES_SICOES.SICOES_TC_REQ_APROBACION 
    ( 
     ID_REQ_APROBACION
    ) 
;

ALTER TABLE SICOES_TZ_HIST_EST_APROB_CAMPO 
    ADD CONSTRAINT FK_H_GRUPO_TRAB_RN_LIS_DET FOREIGN KEY 
    ( 
     ID_GRUPO_LD
    ) 
    REFERENCES ES_SICOES.SICOES_TM_LISTADO_DETALLE 
    ( 
     ID_LISTADO_DETALLE
    ) 
;


ALTER TABLE SICOES_TZ_HIST_EST_APROB_CAMPO 
    ADD CONSTRAINT FK_H_GR_APROB_RN_LIS_DET FOREIGN KEY 
    ( 
     ID_GRUPO_APROBADOR_LD
    ) 
    REFERENCES ES_SICOES.SICOES_TM_LISTADO_DETALLE 
    ( 
     ID_LISTADO_DETALLE
    ) 
;


ALTER TABLE SICOES_TZ_HIST_EST_INVITACION 
    ADD CONSTRAINT FK_ESTADO_HIST_INVITACION_01 FOREIGN KEY 
    ( 
     ID_REQ_INVITACION
    ) 
    REFERENCES ES_SICOES.SICOES_TC_REQ_INVITACION 
    ( 
     ID_REQ_INVITACION
    ) 
;

ALTER TABLE SICOES_TZ_HIST_EST_REQ_RENOV 
    ADD CONSTRAINT FK_ESTADO_REQUERIMIENTO FOREIGN KEY 
    ( 
     ID_REQUERIMIENTO
    ) 
    REFERENCES SICOES_TC_REQ_RENOVACION 
    ( 
     ID_REQ_RENOVACION
    ) 
;

ALTER TABLE SICOES_TZ_HIST_EST_REQ_RENOV 
    ADD CONSTRAINT FK_ESTADO_USUARIO FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES ES_SICOES.SICOES_TM_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

ALTER TABLE SICOES_TZ_HIST_EST_REQ_RENOV 
    ADD CONSTRAINT FK_H_EANT_REQNOV_RN_LIS_DET FOREIGN KEY 
    ( 
     DE_ESTADO_ANTERIOR_LD
    ) 
    REFERENCES ES_SICOES.SICOES_TM_LISTADO_DETALLE 
    ( 
     ID_LISTADO_DETALLE
    ) 
;


ALTER TABLE SICOES_TZ_HIST_EST_REQ_RENOV 
    ADD CONSTRAINT FK_H_ENUV_REQNOV_RN_LIS_DET FOREIGN KEY 
    ( 
     DE_ESTADO_NUEVO_LD
    ) 
    REFERENCES ES_SICOES.SICOES_TM_LISTADO_DETALLE 
    ( 
     ID_LISTADO_DETALLE
    ) 
;



ALTER TABLE SICOES_TZ_HIST_EST_APROB_CAMPO 
    ADD CONSTRAINT FK_ESTADO_USUARIOv1 FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES ES_SICOES.SICOES_TM_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

-- Agregar nuevas columnas a la tabla SICOES_TC_REQ_INVITACION
ALTER TABLE "ES_SICOES"."SICOES_TC_REQ_INVITACION" 
ADD (
    "ID_REQ_RENOVACION" NUMBER(38),
    "ID_NOTIFICACION" NUMBER(38),
    "ID_PLAZO_CONFIRMACION" NUMBER(38),
    "FE_CANCELADO" DATE
);

ALTER TABLE ES_SICOES.SICOES_TC_REQ_INVITACION 
    ADD CONSTRAINT FK_ID_PLAZO_CONFIRMACION FOREIGN KEY 
    ( 
     ID_PLAZO_CONFIRMACION
    ) 
    REFERENCES SICOES_TM_PLAZO_CONFIRMACION 
    ( 
     ID_PLAZO_CONFIRMACION
    ) 
;

ALTER TABLE ES_SICOES.SICOES_TC_REQ_INVITACION 
    ADD CONSTRAINT SICOES_ID_REQ_RENOVACION_FK FOREIGN KEY 
    ( 
     ID_REQ_RENOVACION
    ) 
    REFERENCES SICOES_TC_REQ_RENOVACION 
    ( 
     ID_REQ_RENOVACION
    ) 
;

ALTER TABLE ES_SICOES.SICOES_TC_REQ_INVITACION 
    ADD CONSTRAINT SCS_TC_REQ_INV_TR_NOT_FK FOREIGN KEY 
    ( 
     ID_NOTIFICACION
    ) 
    REFERENCES ES_SICOES.SICOES_TR_NOTIFICACION 
    ( 
     ID_NOTIFICACION
    ) 
;


ALTER TABLE SICOES_TZ_INF_PRESUPUESTAL 
    ADD CONSTRAINT FK_INF_P_REQ_APROBACION FOREIGN KEY 
    ( 
     ID_REQ_APROBACION
    ) 
    REFERENCES ES_SICOES.SICOES_TC_REQ_APROBACION 
    ( 
     ID_REQ_APROBACION
    ) 
;

ALTER TABLE SICOES_TD_INFORME_RENOVACION 
    ADD CONSTRAINT FK_INF_REQ_RENO FOREIGN KEY 
    ( 
     ID_REQUERIMIENTO
    ) 
    REFERENCES SICOES_TC_REQ_RENOVACION 
    ( 
     ID_REQ_RENOVACION
    ) 
;


-- Agregar nuevas columnas a la tabla SICOES_TC_REQ_APROBACION
ALTER TABLE "ES_SICOES"."SICOES_TC_REQ_APROBACION" 
ADD (
    "ID_INFORME_RENOVACION" NUMBER(38),
    "ID_NOTIFICACION" NUMBER(38)
);

ALTER TABLE ES_SICOES.SICOES_TC_REQ_APROBACION 
    ADD CONSTRAINT FK_REQ_APRO_INF_RENO FOREIGN KEY 
    ( 
     ID_INFORME_RENOVACION
    ) 
    REFERENCES SICOES_TD_INFORME_RENOVACION 
    ( 
     ID_INFORME_RENOVACION
    ) 
;

ALTER TABLE ES_SICOES.SICOES_TC_REQ_APROBACION 
    ADD CONSTRAINT SCS_TC_AP_TR_NOT_FK FOREIGN KEY 
    ( 
     ID_NOTIFICACION
    ) 
    REFERENCES ES_SICOES.SICOES_TR_NOTIFICACION 
    ( 
     ID_NOTIFICACION
    ) 
;


ALTER TABLE SICOES_TC_REQ_RENOVACION 
    ADD CONSTRAINT FK_REQ_RENO_USU FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES ES_SICOES.SICOES_TM_USUARIO 
    ( 
     ID_USUARIO
    ) 
;


ALTER TABLE SICOES_TD_INFORME_RENOVACION 
    ADD CONSTRAINT FK_ES_INF_RN_LIS_DET FOREIGN KEY 
    ( 
     ES_APROBACION_INFORME
    ) 
    REFERENCES ES_SICOES.SICOES_TM_LISTADO_DETALLE 
    ( 
     ID_LISTADO_DETALLE
    ) 
;

ALTER TABLE SICOES_TC_REQ_RENOVACION 
    ADD CONSTRAINT FK_TC_EST_GPPM_REN_LIST_DET FOREIGN KEY 
    ( 
     ES_APROBACION_GPPM
    ) 
    REFERENCES ES_SICOES.SICOES_TM_LISTADO_DETALLE 
    ( 
     ID_LISTADO_DETALLE
    ) 
;

ALTER TABLE SICOES_TC_REQ_RENOVACION 
    ADD CONSTRAINT FK_TC_EST_GSE_REN_LIST_DET FOREIGN KEY 
    ( 
     ES_APROBACION_GSE
    ) 
    REFERENCES ES_SICOES.SICOES_TM_LISTADO_DETALLE 
    ( 
     ID_LISTADO_DETALLE
    ) 
;

ALTER TABLE SICOES_TC_REQ_RENOVACION 
    ADD CONSTRAINT FK_TC_EST_RENOV_LISTADO_DET FOREIGN KEY 
    ( 
     ES_REQ_RENOVACION
    ) 
    REFERENCES ES_SICOES.SICOES_TM_LISTADO_DETALLE 
    ( 
     ID_LISTADO_DETALLE
    ) 
;

ALTER TABLE SICOES_TC_REQ_RENOVACION 
    ADD CONSTRAINT FK_TC_SOLI_PERF_CONT FOREIGN KEY 
    ( 
     ID_SOLI_PERF_CONT
    ) 
    REFERENCES ES_SICOES.SICOES_TC_SOLI_PERF_CONT 
    ( 
     ID_SOLI_PERF_CONT
    ) 
;


ALTER TABLE SICOES_TD_INFORME_RENOVACION 
    ADD CONSTRAINT SICOES_INFO_TR_NOTIFICACION_FK FOREIGN KEY 
    ( 
     ID_NOTIFICACION
    ) 
    REFERENCES ES_SICOES.SICOES_TR_NOTIFICACION 
    ( 
     ID_NOTIFICACION
    ) 
;

ALTER TABLE SICOES_TD_INFORME_RENOVACION 
    ADD CONSTRAINT SICOES_TX_SICOES_TM_USUARIO_FK FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES ES_SICOES.SICOES_TM_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

