-- Secuencia para SICOES_TC_REQ_RENOVACION
CREATE SEQUENCE SEQ_SICOES_TC_REQ_RENOVACION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para SICOES_TD_INFORME_RENOVACION
CREATE SEQUENCE SEQ_SICOES_TD_INF_RENOVACION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para SICOES_TM_PLAZO_CONFIRMACION
CREATE SEQUENCE SEQ_SICOES_TM_PLAZO_CONF
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para SICOES_TZ_HIST_EST_APROB_CAMPO
CREATE SEQUENCE SEQ_SICOES_HIST_EST_APROB
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para SICOES_TZ_HIST_EST_INVITACION
CREATE SEQUENCE SEQ_SICOES_HIST_EST_INVIT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para SICOES_TZ_HIST_EST_REQ_RENOV
CREATE SEQUENCE SEQ_SICOES_HIST_EST_CAMPO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para SICOES_TZ_INF_PRESUPUESTAL
CREATE SEQUENCE SEQ_SICOES_INF_PRESUP
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;