UPDATE SICOES_TM_LISTADO_DETALLE SET 
DE_VALOR='Certificacion'
WHERE CO_LISTADO_DETALLE='CERTIFICACION';

UPDATE SICOES_TM_LISTADO_DETALLE SET 
DE_VALOR='Acreditacion'
WHERE CO_LISTADO_DETALLE='ACREDITACION';


UPDATE  SICOES_TM_LISTADO_DETALLE SET
NO_LISTADO_DETALLE='PN Profesional',
DE_LISTADO_DETALLE='PN Profesional',
DE_VALOR ='PN Profesional'
WHERE CO_LISTADO_DETALLE='PN_PERS_PROPUESTO';


INSERT INTO "SICOES_TM_LISTADO_DETALLE" (ID_LISTADO_DETALLE, ID_LISTADO, CO_LISTADO_DETALLE, NU_ORDEN, NO_LISTADO_DETALLE, DE_LISTADO_DETALLE, DE_VALOR, US_CREACION, FE_CREACION, IP_CREACION) VALUES ('830', '3', 'CONSTANCIA', '4', 'Constancia', 'Constancia', 'Constancia', 'SICOES', sysdate, '127.0.0.1');
INSERT INTO "SICOES_TM_LISTADO_DETALLE" (ID_LISTADO_DETALLE, ID_LISTADO, CO_LISTADO_DETALLE, NU_ORDEN, NO_LISTADO_DETALLE, DE_LISTADO_DETALLE, DE_VALOR, US_CREACION, FE_CREACION, IP_CREACION) VALUES ('831', '3', 'CERTIFICADO', '5', 'Certificado', 'Certificado', 'Certificado', 'SICOES', sysdate, '127.0.0.1');
INSERT INTO "SICOES_TM_LISTADO_DETALLE" (ID_LISTADO_DETALLE, ID_LISTADO, CO_LISTADO_DETALLE, NU_ORDEN, NO_LISTADO_DETALLE, DE_LISTADO_DETALLE, DE_VALOR, US_CREACION, FE_CREACION, IP_CREACION) VALUES ('832', '3', 'OTROS', '6', 'Otros', 'Otros', 'Otros', 'SICOES', sysdate, '127.0.0.1');
INSERT INTO "SICOES_TM_LISTADO_DETALLE" (ID_LISTADO_DETALLE, ID_LISTADO, CO_LISTADO_DETALLE, NU_ORDEN, NO_LISTADO_DETALLE, DE_LISTADO_DETALLE, DE_VALOR, US_CREACION, FE_CREACION, IP_CREACION) VALUES ('834', '44', 'BLOQUEADO', '4', 'Bloqueado', 'Bloqueado', 'Bloqueado', 'SICOES', sysdate, '127.0.0.1');

INSERT INTO "ES_SICOES"."SICOES_TM_LISTADO_DETALLE" (ID_LISTADO_DETALLE, ID_LISTADO, CO_LISTADO_DETALLE, NU_ORDEN, NO_LISTADO_DETALLE, DE_LISTADO_DETALLE, DE_VALOR, US_CREACION, FE_CREACION, IP_CREACION) VALUES ('835', '25', 'TA21', '21', 'Archivo de Informe Tecnico', 'Archivo de Informe Tecnico', 'Archivo de Informe Tecnico', 'SICOES', sysdate, '127.0.0.1');


UPDATE SICOES_TM_CONF_BANDEJA
SET ID_TIPO_CONF=836;

COMMIT;